name: Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger the deployment on pushes to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment that will run this job

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Build the Spring Boot application using Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Add SSH key to GitHub Actions to SSH into EC2
    - name: Add SSH key to GitHub Actions
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Using the private key stored in GitHub Secrets

    # Copy the built JAR file to EC2 instance
    - name: Copy JAR file to EC2
      run: scp -i /tmp/private_key -o StrictHostKeyChecking=no target/*.jar ec2-user@3.111.197.141:/home/ec2-user/

    # SSH into EC2 and run the application
    - name: SSH into EC2 and run the application
      run: |
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no ec2-user@YOUR_EC2_PUBLIC_IP 'nohup java -jar /home/ec2-user/*.jar &'
