name: Deploy Spring Boot Application to EC2 Linux Machine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "server connected"
          sudo yum update -y
          sudo git clone -b master https://Ramakrishna199828:${{ secrets.MY_GIT_PAT }@github.com/Ramakrishna199828/SpringOnEC2.git
          # cd SpringOnEC2 || git clone https://github.com/Ramakrishna199828/SpringOnEC2.git && cd SpringOnEC2
          # git pull origin master
          
          sudo pkill -f 'java -jar' || echo "No app running"
          cd SpringOnEC2
          # mvn clean install
          ./mvnw clean package
          nohup java -jar target/*.jar > app.log 2>&1 &

