name: Deploy Spring Boot Application to EC2 Linux Machine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Server connected successfully."
          
          sudo yum update -y
          
          # Remove existing folder if it exists (optional safety)
          rm -rf SpringOnEC2
          
          # Correct git clone with PAT (Personal Access Token)
          git clone -b master https://${{ secrets.MY_GIT_PAT }}@github.com/Ramakrishna199828/SpringOnEC2.git
          
          # Stop existing running Spring Boot application
          pkill -f 'java -jar' || echo "No running app to kill."
          
          cd SpringOnEC2
          
          # # Build the application
          # ./mvnw clean package
          
          # # Run the application in the background
          # nohup java -jar target/*.jar > app.log 2>&1 &

          mvn clean install

          nohup java -jar target/*.jar > app.log 2>&1 &

          
